version: "3"

services:

  soft:
    build: docker-compose/soft/
    restart: always
    expose:
      - 8888
    ports:
      - 8888:8888
    depends_on:
      - postgres_db
    links:
      - postgres_db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=postroot
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      -
  postgres_db:
    image: postgres:latest
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=postroot
    restart: always



