spring.jpa:
  database: POSTGRESQL

spring.datasource:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://127.0.0.1:5432/projectSoft_bd
  username: root
  password: postroot

server:
  port: 8888
  servlet:
    context-path: /soft
spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

