spring.jpa:
  database: POSTGRESQL

spring.datasource:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/projectSoft_bd
  username: root
  password: postroot

server:
  port: 8888
  servlet:
    context-path: /soft
spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

  security:
    user:
      name: test
      password: $2a$10$U9NZV6x1QaQYac36xqgj/O.oBeN/veJeLdwwqC02RH1Vv8PSAU2Ai
      roles: TEST

